print("First Name:", end="")
first_name = input()
print("Last Name:", end="")
last_name = input()
print("Age:", end="")
age = input()
print(f"Your name is {first_name} {last_name} and you are {age} years of age.")